export const MAX_CONTENT_WIDTH = 680;
export const DETAIL_HERO_LANDSCAPE_RATIO = 0.4;
export const LIST_CONTENT_WIDTH_LANDSCAPE_RATIO = 0.7;
export const LIST_MAX_CONTENT_WIDTH_LANDSCAPE = 960;
export const TABLET_BREAKPOINT = 600;
export const MAX_CONTENT_WIDTH_TABLET = 900;
